apiVersion: apps/v1
kind: Doployment
metadata:
  name: sample-deployment-rollingupdate
spec:
  strategiy:
    type: RollyingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12

