apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-app
  name: sample-app
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-app
  type: NodePort
status:
  loadBalancer: {}
