# permissions for end users to edit memcacheds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcached-editor-role
rules:
- apiGroups:
  - cache.hirooka.dev
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.hirooka.dev
  resources:
  - memcacheds/status
  verbs:
  - get
