apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sample-cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  # Kube Masterが死んでいた場合に実行を許容する秒数。デフォルトではどれだけ遅れても実行する。
  startingDeadlineSeconds: 30
  # 成功したJobを保存しておく数(紐づくPodも残っている)
  successfulJobsHistoryLimit: 5
  # 失敗したJobを保存しておく数(紐づくPodも残っている)
  failedJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: sleep-container
            image: centos:6
            command:
            - "sh"
            - "-c"
            args:
            # 50%の確率で成功するコマンド
            - "sleep 40; date + '%N' | cut -c 9 | egrep '[1|3|5|7|9]'"
          restartPolicy: Never

